### ISSUE TITLE
Blank Default Page

### ISSUE THREAD

**Issue by rosman83** [chawk/bare_bones_react#9]
Hey,

I'm following the Advanced React tutorial you created in which you instruct to use this bare bones react project. After cloning it and starting it with the relevant script in local host port 9081 - It does not show the usual Bare Bones React Page and is instead a blank page with a few errors in the browser. I usually use create react app just fine so I've never had an issue with hosting local react projects. Since I'm seeing the last commit was nearly 8 months ago - is it because some aspect of this project is now outdated or something? Just want to make sure this isn't a problem on my end - Cheers!

**Comment by rosman83** [comment]
Reopened this at the request of Chris on youtube. 
After cloning - running NPM install - and starting a dev server on port 9081 it will be a blank page with the following errors in chrome dev tool.

```- C:\Users\Name\Desktop\projects\development\easytemp\bare_bones_react\node_modules\sass-loader\lib\loader.js
- C:\Users\Name\Desktop\projects\development\easytemp\bare_bones_react\node_modules\loader-runner\lib\loadLoader.js
- C:\Users\Name\Desktop\projects\development\easytemp\bare_bones_react\node_modules\loader-runner\lib\LoaderRunner.js
- C:\Users\Name\Desktop\projects\development\easytemp\bare_bones_react\node_modules\webpack\lib\NormalModule.js
- C:\Users\Name\Desktop\projects\development\easytemp\bare_bones_react\node_modules\webpack\lib\NormalModuleFactory.js
- C:\Users\Name\Desktop\projects\development\easytemp\bare_bones_react\node_modules\webpack\lib\Compiler.js
- C:\Users\Name\Desktop\projects\development\easytemp\bare_bones_react\node_modules\webpack\lib\webpack.js
- C:\Users\Name\Desktop\projects\development\easytemp\bare_bones_react\node_modules\webpack-cli\bin\utils\validate-options.js
- C:\Users\Name\Desktop\projects\development\easytemp\bare_bones_react\node_modules\webpack-cli\bin\utils\convert-argv.js
- C:\Users\Name\Desktop\projects\development\easytemp\bare_bones_react\node_modules\webpack-cli\bin\cli.js
- C:\Users\Name\Desktop\projects\development\easytemp\bare_bones_react\node_modules\webpack\bin\webpack.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (C:\Users\Name\Desktop\projects\development\easytemp\bare_bones_react\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at Object.sassLoader (C:\Users\Name\Desktop\projects\development\easytemp\bare_bones_react\node_modules\sass-loader\lib\loader.js:46:72)
    at C:\Users\Name\Desktop\projects\development\easytemp\bare_bones_react\node_modules\webpack\lib\NormalModule.js:301:20
    at C:\Users\Name\Desktop\projects\development\easytemp\bare_bones_react\node_modules\loader-runner\lib\LoaderRunner.js:364:11
    at C:\Users\Name\Desktop\projects\development\easytemp\bare_bones_react\node_modules\loader-runner\lib\LoaderRunner.js:230:18
    at runSyncOrAsync (C:\Users\Name\Desktop\projects\development\easytemp\bare_bones_react\node_modules\loader-runner\lib\LoaderRunner.js:143:3)
    at iterateNormalLoaders (C:\Users\Name\Desktop\projects\development\easytemp\bare_bones_react\node_modules\loader-runner\lib\LoaderRunner.js:229:2)
    at Array.<anonymous> (C:\Users\Name\Desktop\projects\development\easytemp\bare_bones_react\node_modules\loader-runner\lib\LoaderRunner.js:202:4)
    at Storage.finished (C:\Users\Name\Desktop\projects\development\easytemp\bare_bones_react\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:43:16)
    at C:\Users\Name\Desktop\projects\development\easytemp\bare_bones_react\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:79:9
    at C:\Users\Name\Desktop\projects\development\easytemp\bare_bones_react\node_modules\graceful-fs\graceful-fs.js:90:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
    at Object../ui/sass/main.scss (http://localhost:9081/static/js/app.bundle.js:29633:7)
    at __webpack_require__ (http://localhost:9081/static/js/app.bundle.js:724:30)
    at fn (http://localhost:9081/static/js/app.bundle.js:101:20)
    at Module../ui/index.js (http://localhost:9081/static/js/app.bundle.js:29532:73)
    at __webpack_require__ (http://localhost:9081/static/js/app.bundle.js:724:30)
    at http://localhost:9081/static/js/app.bundle.js:791:51
    at http://localhost:9081/static/js/app.bundle.js:794:10
:9081/favicon.ico:1 Failed to load resource: the server responded with a status of 404 (Not Found)
localhost/:1 Refused to apply style from 'http://localhost:9081/static/css/style.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.```
